# no version needed since 2020
services:
  jekyll:
    image: bretfisher/jekyll-serve
    container_name: mmc-staff
    working_dir: /srv
    volumes:
      - .:/srv
    ports:
      - '5744:5744'
      - '35744:35744'
    command: bundle exec jekyll s --trace --force_polling -H 0.0.0.0 -P 5744 -l --livereload-port 35744
